# Podfile

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use node_require to load RN's script and react-native-permissions setup
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RTE' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # -----------------------------
  # react-native-permissions setup
  # only permissions specified here will be added to the Podfile
  # -----------------------------
  setup_permissions([
    'PhotoLibrary',
    'PhotoLibraryAddOnly',
    # uncomment any additional ones you need:
    # 'Camera',
    # 'Microphone',
    # 'LocationWhenInUse',
    # 'LocationAlways',
    # 'Notifications',
    # 'MediaLibrary',
  ])

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # keep compatibility workarounds if present in your project
    if respond_to?(:__apply_Xcode_12_5_M1_post_install_workaround)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    end
  end
end
