export const Routes = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  HOME: 'HOME',
  CALANDER: 'Calander',
  ADD_CALENDAR_MILES: 'AddCalendarMiles',
  TEAMS: 'Teams',
  SETTING: 'Setting',
  PROFILE: 'Profile',
  GRAPH: 'Graph',
  TROPHY: 'TROPHY',
  PASSWORD: 'PasswordContainer',
  DEVICE_SYNC: 'DeviceSync',
  CONNECT_DEVICE: 'ConnectDevice',
  DISCONNECT_DEVICE: 'DisconnectDevice',
  SAMSUNG_HEALTH_SETTINGS: 'SamsungHealthSettings',
  SAMSUNG_HEALTH_DEBUG: 'SamsungHealthDebug',
  OURA_RING_SETTINGS: 'OuraRingSettings',
  NOTIFICATIONS: 'NotificationsContainer',
  MANUAL_ENTRY: 'ManualEntryContainer',
  PRIVACY: 'PrivacyContainer',
  TEAM_STACK: 'TeamStack',
  CREATE_TEAM: 'CreateTeamContainer',
  JOIN_TEAM: 'JoinTeamContainer',
  MANAGE_TEAM: 'ManageTeamContainer',
  MEMEBR_ON_TEAM: 'MemberonTeam',
  //Quest Screens
  QUEST_OPTIONS: 'QuestOptionsContainer',
  JOURNEL: 'JournelContainer',
  SCHEDULE_QUEST: 'ScheduleQuestContainer',
  REGISTERED_QUEST: 'RegisteredQuest',
  MANAGE_QUEST: 'ManageQuestContainer',
  MEETING_MENTOR: 'MeetingMentor',
  QUEST_HISTORY: 'QuestHistoryContainer',

  //Settings Screens
  IMPORT: 'ImportContainer',
  GOALS: 'GoalsContainer',
  TRACKER_ATTITUDE: 'TrackerAttitude',
  TUTORIAL: 'TutorialsContainer',

  //Navigations
  PUBLIC_NAVIGATOR: 'PublicNavigator',
  SETTING_STACK: 'SettingStack',
  CALENDAR_STACK: 'CalendarStack',
  QUEST_STACK: 'QuestStack',
  HOME_STACK: 'HomeStack',
  GRAPH_STACK: 'GraphStack',
  TROPHY_STACK: 'TrophyStack',

  // Stats Screens
  FOLLOW: 'FollowContainer',
};
